name: Python tests Ubuntu-20.04 (frozen)
# This workflow is triggered on pushes and PRs to the repository.
# Only run if we changed a Python file
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: Check out source-code repository

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip -r requirements-dev.txt
          pip install -e .

      - name: Downgrade git to the Ubuntu official repository's version
        run: |
          sudo apt remove git git-man
          sudo add-apt-repository --remove ppa:git-core/ppa
          sudo apt install git

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest-everything"

      - name: Test with pytest
        run: python3 -m pytest tests/ --color=yes --cov-report=xml --cov-config=.github/.coveragerc --cov=nf_core

      - uses: codecov/codecov-action@v1
        name: Upload code coverage report
        with:
          if: success()
          token: ${{ secrets.CODECOV_TOKEN }}
